version: '3'
services:
# At installation process (type in postgres) as database location
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=limesurvey
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - .:/limesurvey
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  php:
    container_name: php
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - .:/limesurvey
