version: '3'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/db/data
      #- ./docker/data/db/data/pgdata:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=limesurvey
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - .:/limesurvey
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  php:
    container_name: php
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - .:/limesurvey
